[package]
name = "match_linestrings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
geo = { workspace = true }
geojson = { workspace = true }
rstar = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utils = { workspace = true }
